FROM python:3.12-slim

WORKDIR /app/

COPY api.py db.py embedding.py requirements.txt /app/

#RUN apt-get update && apt-get upgrade -y && apt-get install -y --no-install-recommends gcc && \
#pip install --upgrade pip && \
#pip install -r requirements.txt && \
#apt-get purge -y --auto-remove gcc && \
#rm -rf /var/lib/apt/lists/*
RUN pip install -r requirements.txt

EXPOSE 8000

CMD ["python","api.py"]